module.exports = {
  siteMetadata: {
    title: 'Snowball Securities',
    description: 'Snowball Securities Description',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass',
    `gatsby-plugin-flow`,
    {
      // keep as first gatsby-source-filesystem plugin for gatsby image support
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/static/img`,
        name: 'uploads',
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/img`,
        name: 'images',
      },
    },
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-relative-images',
            options: {
              name: 'uploads',
            },
          },
          {
            resolve: 'gatsby-remark-images',
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 1500,
            },
          },
          {
            resolve: 'gatsby-remark-copy-linked-files',
            options: {
              destinationDir: 'static',
            },
          },
        ],
      },
    },
    {
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`,
      },
    },
    `gatsby-plugin-sass`,
    // {
    //   resolve: 'gatsby-plugin-purgecss', // purges all unused/unreferenced css rules
    //   options: {
    //     ignore: ['slick/', 'slick-carousel/slick', 'reactstrap', ''],
    //     develop: true, // Activates purging in npm run develop
    //     whitelist: [
    //       'navbar-toggler-icon',
    //       'navbar-toggler',
    //       'jumbotron',
    //       'carousel-indicators',
    //       'carousel',
    //       'slide',
    //       'carousel-inner',
    //       'carousel-item',
    //       'no-gutters',
    //       'row',
    //       'w-100',
    //       'h-100',
    //       'btn',
    //       'btn-outline-primary',
    //       'btn-primary',
    //       'col',
    //       'col-1',
    //       'col-2',
    //       'col-3',
    //       'col-4',
    //       'col-5',
    //       'col-6',
    //       'col-7',
    //       'col-8',
    //       'col-9',
    //       'col-10',
    //       'col-11',
    //       'col-12',
    //       'col-md-1',
    //       'col-md-2',
    //       'col-md-3',
    //       'col-md-4',
    //       'col-md-5',
    //       'col-md-6',
    //       'col-md-7',
    //       'col-md-8',
    //       'col-md-9',
    //       'col-md-10',
    //       'col-md-11',
    //       'col-md-12',
    //       'col-lg-1',
    //       'col-lg-2',
    //       'col-lg-3',
    //       'col-lg-4',
    //       'col-lg-5',
    //       'col-lg-6',
    //       'col-lg-7',
    //       'col-lg-8',
    //       'col-lg-9',
    //       'col-lg-10',
    //       'col-lg-11',
    //       'col-lg-12',
    //       'col-xl-1',
    //       'col-xl-2',
    //       'col-xl-3',
    //       'col-xl-4',
    //       'col-xl-5',
    //       'col-xl-6',
    //       'col-xl-7',
    //       'col-xl-8',
    //       'col-xl-9',
    //       'col-xl-10',
    //       'col-xl-11',
    //       'col-xl-12',
    //       'h1',
    //       'h2',
    //       'h3',
    //       'h4',
    //       'h5',
    //       'form-group',
    //       'form-control',
    //       'collapse',
    //       'nav',
    //       'navbar-nav',
    //       'navbar-toggler',
    //       'navbar-collapse',
    //       'navbar-expand-md',
    //       'navbar-light',
    //       'bg-light',
    //       'nav-link',
    //       'collapsing',
    //       'show',
    //       'card',
    //       'card-body',
    //       'card-img',
    //       'carousel',
    //       'slide',
    //       'carousel-inside',
    //       'carousel-control-prev',
    //       'carousel-control-prev-icon',
    //       'sr-only',
    //       'carousel-control-next',
    //       'carousel-control-next-icon',
    //       'carousel-item-left',
    //       'carousel-item-right',
    //       'active',
    //       'modal',
    //       'modal-body',
    //       'modal-content',
    //       'modal-lg',
    //       'slick'
    //     ],
    //   },
    // }, // must be after other CSS plugins
    'gatsby-plugin-netlify', // make sure to keep it last in the array
    `gatsby-plugin-styled-components`,
    {
      resolve: 'gatsby-plugin-page-transitions',
      options: {
        transitionTime: 800,
      },
    },
  ],
}
